### ISSUE TITLE
Bug: multiple CHEF-19 violations in resources

### ISSUE THREAD

**Issue by rmiesen** [jenssegers/chef-file#24]
Hi.

Recently I encountered an issue where chef-client version 13.6.4 threw a [CHEF-19](https://docs.chef.io/deprecations_namespace_collisions.html) depreciation warning in the following resources:
 1. replace_line, lines 13, 16, 19, and 29.
 2. Append_line, lines 12 and 15.

I briefly looked at the other resources and they all contain similar violations. This is an issue because starting with Chef 14.0 (releases April 1st), these deprecations will become errors.

**Comment by WautersPh** [comment]
Good morning,

I am facing the same issue and wonder if a new release of the "patch" cookbook is in the pipeline.

Here is an example of the warnings I get:

Deprecated features used!
  rename file to new_resource.file at 1 location:
    - /home/bfc586/.chef/local-mode-cache/cache/cookbooks/patch/resources/replace.rb:13:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename path to new_resource.path at 1 location:
    - /home/bfc586/.chef/local-mode-cache/cache/cookbooks/patch/resources/replace.rb:13:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename name to new_resource.name at 1 location:
    - /home/bfc586/.chef/local-mode-cache/cache/cookbooks/patch/resources/replace.rb:13:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename replace to new_resource.replace at 2 locations:
    - /home/bfc586/.chef/local-mode-cache/cache/cookbooks/patch/resources/replace.rb:16:in `block in class_from_file'
    - /home/bfc586/.chef/local-mode-cache/cache/cookbooks/patch/resources/replace.rb:19:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.

This can easily be fixed by doing exactly what is reported : "rename file to new_resource.file" ... for instance.

Any hope to get a new release of this cookbook soon ?

Kind regards.

Philippe
