### ISSUE TITLE
Though replace works it says Deprecated version

### ISSUE THREAD

**Issue by bhai840** [jenssegers/chef-file#25]
I am using chef: 13.8.5, when I tun your resources it says Deprecated feature used. Is there any way to get it fixed?

Recipe: test::default
  * replace_line[/etc/ssh/sshd_config] action run (up to date)

Running handlers:
Running handlers complete

Deprecated features used!
  rename file to new_resource.file at 1 location:
    - /root/.chef/local-mode-cache/cache/cookbooks/test/resources/replace_line.rb:13:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename path to new_resource.path at 1 location:
    - /root/.chef/local-mode-cache/cache/cookbooks/test/resources/replace_line.rb:13:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename name to new_resource.name at 1 location:
    - /root/.chef/local-mode-cache/cache/cookbooks/test/resources/replace_line.rb:13:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename replace to new_resource.replace at 2 locations:
    - /root/.chef/local-mode-cache/cache/cookbooks/test/resources/replace_line.rb:16:in `block in class_from_file'
    - /root/.chef/local-mode-cache/cache/cookbooks/test/resources/replace_line.rb:19:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.

**Comment by bhai840** [comment]
Fixed it by adding new_resource.replace,new_resource.file, new_resource.path,new_resource.name  to deprecated version replace, file, path,name 

 file_path = new_resource.file || new_resource.path || new_resource.name
     
              # Check if we got a regex or a string
              if new_resource.replace.is_a?(Regexp)
                      regex = new_resource.replace
              else
                      regex = Regexp.new(Regexp.escape(new_resource.replace))
              end
